INSERT INTO globalization.localize_team (id, creation_date, modification_date, tags, version,  description, invoice_category, invoice_region, slack_channel, name) VALUES ('team1', '2022-02-01 15:42:49.000000', '2022-02-01 15:42:52.000000', '{test,notifications}', 3, 'this is a cool team', 'direct', 'APAC', '#los_locos', 'los locos');

INSERT INTO globalization.localize_project (id, creation_date, modification_date, tags, version, consumer_channel, contact_email, content_type, contexturl, creation_user, description, invoice_category, invoice_region, modification_user, name, require_review,slack_channel, source_language, target_languages, team_id) VALUES ('project1', '2022-02-01 15:42:49.000000', '2022-02-01 15:42:52.000000', '{tag1,tag2}', 3, 'martech', 'john.chrislomeli@chrislomeli.com', 'push notification', 'http://context.com', 'chris', 'Order Content', 'direct', 'APAC', 'joe', 'Order Process', 'YES','#loslocos-dev', 'en', '{en,fr,sv}', 'team1');
--
INSERT INTO globalization.localize_document (id, creation_date, modification_date, tags, version, consumer_channel, contact_email, content_type, contexturl, creation_user, description, invoice_category, invoice_region, modification_user, name, require_review, slack_channel,source_language, target_languages, project_id) VALUES ('document1', '2022-02-01 15:42:49.000000', '2022-02-01 15:42:52.000000', '{tag1,tag2}', 3, 'martech', 'john.chrislomeli@chrislomeli.com', 'push notification', 'http://context.com', 'chris', 'Order confirmation notification', 'direct', 'APAC', 'joe', 'Order Confirmation', 'YES', '#loslocos-dev', 'en', '{en,fr,sv}', 'project1');

INSERT INTO globalization.localize_string (id, creation_date, modification_date, tags, version, description, file_link_id, instructions, key, status, document_id) VALUES ('greeting-string1', '2022-02-01 21:27:29.000000', '2022-02-01 21:27:32.000000', '{tagr2,tagr2}', 3, 'Greeting', 'http://context.com', 'Basic formal salutation', 'GREETING', 'UNKNOWN', 'document1');
INSERT INTO globalization.localize_string (id, creation_date, modification_date, tags, version, description, file_link_id, instructions, key, status, document_id) VALUES ('delivery-string1', '2022-02-01 21:27:29.000000', '2022-02-01 21:27:32.000000', '{tagr2,tagr2}', 3, 'Delivery date', 'http://context.com', 'Delivered on {{delivery_date}}', 'DELIVERY_DATE', 'UNKNOWN', 'document1');
INSERT INTO globalization.localize_string (id, creation_date, modification_date, tags, version, description, file_link_id, instructions, key, status, document_id) VALUES ('cta-string1', '2022-02-01 21:27:29.000000', '2022-02-01 21:27:32.000000', '{tagr2,tagr2}', 3, 'Call to action', 'http://context.com', 'User can press button to acknowlege delivery', 'CTA', 'UNKNOWN', 'document1');

INSERT INTO globalization.localize_translation (id, creation_date, modification_date, tags, version, description, device, instructions, file_link_id, language, marketplace_id, region, sha256, status, time_of_day, value, string_id) VALUES ('translation1', '2022-02-01 21:36:01.000000', '2022-02-01 21:36:04.000000', '{default}', 3, 'description', '*', 'normal translation', '', 'fr', '*', '*', null, 'NEEDS_TRANSLATION', 'evening', 'BonJour', 'greeting-string1');
INSERT INTO globalization.localize_translation (id, creation_date, modification_date, tags, version, description, device, instructions, file_link_id,language, marketplace_id, region, sha256, status, time_of_day, value, string_id) VALUES ('translation2', '2022-02-01 21:36:01.000000', '2022-02-01 21:36:04.000000', '{default}', 3, 'description', '*', 'normal translation', '','sv', '*', '*', null, 'NEEDS_TRANSLATION', 'evening', 'hälsningar', 'greeting-string1');
INSERT INTO globalization.localize_translation (id, creation_date, modification_date, tags, version, description, device, instructions, file_link_id,language, marketplace_id, region, sha256, status, time_of_day, value, string_id) VALUES ('translation3', '2022-02-01 21:36:01.000000', '2022-02-01 21:36:04.000000', '{variant}', 3, 'description', '*', 'Finnish variation', '','sv', '*', 'FI', null, 'NEEDS_TRANSLATION', 'evening', 'hallå', 'greeting-string1');
INSERT INTO globalization.localize_translation (id, creation_date, modification_date, tags, version, description, device, instructions, file_link_id,language, marketplace_id, region, sha256, status, time_of_day, value, string_id) VALUES ('translation4', '2022-02-01 21:36:01.000000', '2022-02-01 21:36:04.000000', '{default}', 3, 'description', '*', 'normal translation', '','fr', '*', '*', null, 'NEEDS_TRANSLATION', 'evening', 'délivré le', 'delivery-string1');
INSERT INTO globalization.localize_translation (id, creation_date, modification_date, tags, version, description, device, instructions, file_link_id,language, marketplace_id, region, sha256, status, time_of_day, value, string_id) VALUES ('translation5', '2022-02-01 21:36:01.000000', '2022-02-01 21:36:04.000000', '{default}', 3, 'description', '*', 'normal translation', '','sv', '*', '*', null, 'NEEDS_TRANSLATION', 'evening', 'levererad på', 'delivery-string1');
INSERT INTO globalization.localize_translation (id, creation_date, modification_date, tags, version, description, device, instructions, file_link_id,language, marketplace_id, region, sha256, status, time_of_day, value, string_id) VALUES ('translation65', '2022-02-01 21:36:01.000000', '2022-02-01 21:36:04.000000', '{variant}', 3, 'description', '*', 'Canadian french - informal', '','fr', '*', 'CAN', null, 'NEEDS_TRANSLATION', 'evening', 'leveransdatum', 'delivery-string1');
INSERT INTO globalization.localize_translation (id, creation_date, modification_date, tags, version, description, device, instructions, file_link_id,language, marketplace_id, region, sha256, status, time_of_day, value, string_id) VALUES ('translation7', '2022-02-01 21:36:01.000000', '2022-02-01 21:36:04.000000', '{default}', 3, 'description', '*', 'normal translation', '','fr', '*', '*', null, 'NEEDS_TRANSLATION', 'evening', 'répond sil vous plait', 'cta-string1');
INSERT INTO globalization.localize_translation (id, creation_date, modification_date, tags, version, description, device, instructions, file_link_id,language, marketplace_id, region, sha256, status, time_of_day, value, string_id) VALUES ('translation8', '2022-02-01 21:36:01.000000', '2022-02-01 21:36:04.000000', '{default}', 3, 'description', '*', 'normal translation', '','sv', '*', '*', null, 'NEEDS_TRANSLATION', 'evening', 'vänligen svara', 'cta-string1');

