package com.chrislomeli.localizestore.exception;


public class ParentNotFoundException  {
    //autogenerated by IntelliJ
    private static final long serialVersionUID = -5047068369506472820L;

    public ParentNotFoundException(String s) {

    }
}
